#!/bin/bash

ropts=""
node=""
while (( $# > 0 )); do
case $1 in 
-q) shift; node="@$1"; shift;;
-r) shift; ropts=","$ropts" "$1 ; shift;;
*) echo "Invalid argument"; exit 1
esac
done
export UMASK=`umask`
unset module
qrsh -v LD_LIBRARY_PATH -V -N Mat_UI -q background.q${node} -cwd -b y "umask $UMASK;/apps/matlab14a/bin/matlab -nodisplay -nodesktop -nosplash -singleCompThread"
