[35mdocs/src/ct_hank/kalman_filter/sim_kalman_filter.jl[m[36m:[m    [1;31mupdate![m(m.settings[:state_simulation_freq], Setting(:state_simulation_freq, sim_freqs[j]))
[35mdocs/src/ct_hank/kalman_filter/timing/time_sim_kalman_filter.jl[m[36m:[m    [1;31mupdate![m(m.settings[:state_simulation_freq], Setting(:state_simulation_freq, sim_freqs[j]))
[35mdocs/src/estimation.md[m[36m:[m[1;31mupdate![m(m, params)
[35mdocs/src/model_implementation_details.md[m[36m:[mDSGE.[1;31mupdate![m
[35mdocs/src/special_model_types.md[m[36m:[m  the names of the observables by calling `[1;31mupdate![m` or
[35mexamples/run_dsgevar.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevar, λ = dsgevar_λ)
[35mexamples/run_dsgevar.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevar, observables =
[35mexamples/run_dsgevar.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevar, shocks = collect(keys(m.exogenous_shocks)), observables = collect(keys(m.observables)))
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, modal_paras)
[35mexamples/run_dsgevar.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar, load_draws(dsgevar, :mode))
[35mexamples/run_dsgevar.jl[m[36m:[m        DSGE.[1;31mupdate![m(m,       load_draws(dsgevar, :mode))
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = Inf)
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = dsgevar_λ)
[35mexamples/run_dsgevar.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar; λ = Inf)
[35mexamples/run_dsgevar.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar; λ = dsgevar_λ)
[35mexamples/run_dsgevar.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar, load_draws(dsgevar, :mode))
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = Inf)
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = dsgevar_λ)
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = Inf)
[35mexamples/run_dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar; λ = dsgevar_λ)
[35msrc/abstractdsgemodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m,load_parameters_from_file(m,mode_file))
[35msrc/abstractdsgemodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, new_values)
[35msrc/abstractdsgemodel.jl[m[36m:[m[1;31mupdate![m(m::AbstractDSGEModel, values::Vector{T}) where T<:AbstractFloat
[35msrc/abstractdsgemodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEModel, values::AbstractVector{T}) where {T <: Real}
[35msrc/abstractdsgemodel.jl[m[36m:[m    ModelConstructors.[1;31mupdate![m(m.parameters, values)
[35msrc/abstractdsgemodel.jl[m[36m:[m[1;31mupdate![m(m::AbstractDSGEModel, values::ParameterVector{T};
[35msrc/abstractdsgemodel.jl[m[36m:[m    in which case `[1;31mupdate![m` assumes the `value` field
[35msrc/abstractdsgemodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEModel, values::ParameterVector{T};
[35msrc/abstractdsgemodel.jl[m[36m:[m        ModelConstructors.[1;31mupdate![m(m.parameters, [θ.value for θ in values])
[35msrc/abstractdsgemodel.jl[m[36m:[m        ModelConstructors.[1;31mupdate![m(m.parameters, [θ.value for θ in values])
[35msrc/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, new_values)
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVARModel{T}, values::Vector{T}) where {T<:Real}
[35msrc/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(get_dsge(m), values)
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVARModel{T}, values::ParameterVector{T}) where {T<:Real}
[35msrc/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(get_dsge(m), values)
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVARModel; observables::Vector{Symbol} = Vector{Symbol}(undef, 0),
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVARModel, dsge::AbstractDSGEModel;
[35msrc/abstractvarmodel.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, shocks = shocks, lags = lags,
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVECMModel; observables::Vector{Symbol} = Vector{Symbol}(undef, 0),
[35msrc/abstractvarmodel.jl[m[36m:[mfunction [1;31mupdate![m(m::AbstractDSGEVECMModel, dsge::AbstractDSGEModel;
[35msrc/abstractvarmodel.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, cointegrating = cointegrating,
[35msrc/analysis/moments.jl[m[36m:[m    [1;31mupdate![m(m, θ)
[35msrc/analysis/moments.jl[m[36m:[m        DSGE.[1;31mupdate![m(m, old_param)
[35msrc/analysis/moments.jl[m[36m:[m        [1;31mupdate![m(m, θvec)
[35msrc/decomp/drivers.jl[m[36m:[m      DSGE.[1;31mupdate![m(m, params)
[35msrc/estimate/csminwel.jl[m[36m:[m            Optim.[1;31mupdate![m(tr,
[35msrc/estimate/ct_filters/block_kalman_filter.jl[m[36m:[m        [1;31mupdate![m(k, y[:, t]; return_loglh = return_loglh)
[35msrc/estimate/ct_filters/block_kalman_filter.jl[m[36m:[mfunction [1;31mupdate![m(k::BlockKalmanFilter{Float64}, y_obs::Vector{Float64}; return_loglh::Bool = true)
[35msrc/estimate/ct_filters/ct_block_kalman_filter.jl[m[36m:[m        [1;31mupdate![m(k, y[:, t]; return_loglh = return_loglh)
[35msrc/estimate/ct_filters/ct_block_kalman_filter.jl[m[36m:[mfunction [1;31mupdate![m(k::CTBlockKalmanFilter{Float64}, y_obs::Vector{Float64}; return_loglh::Bool = true)
[35msrc/estimate/ct_filters/ct_kalman_filter.jl[m[36m:[m        StateSpaceRoutines.[1;31mupdate![m(k, y[:, t]; return_loglh = return_loglh)
[35msrc/estimate/ct_filters/ct_kalman_filter.jl[m[36m:[m        StateSpaceRoutines.[1;31mupdate![m(k, y[:, t]; return_loglh = return_loglh)
[35msrc/estimate/hessian.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, x)
[35msrc/estimate/metropolis_hastings.jl[m[36m:[m            [1;31mupdate![m(m, p; regime_switching = regime_switching, toggle = toggle)
[35msrc/estimate/metropolis_hastings.jl[m[36m:[m            [1;31mupdate![m(m, p)
[35msrc/estimate/optimize.jl[m[36m:[m                    DSGE.[1;31mupdate![m(m, x_proposal_all)
[35msrc/estimate/optimize.jl[m[36m:[m                    DSGE.[1;31mupdate![m(m, x_proposal_all)
[35msrc/estimate/posterior.jl[m[36m:[m            DSGE.[1;31mupdate![m(m, parameters; regime_switching = regime_switching, toggle = toggle)
[35msrc/estimate/posterior.jl[m[36m:[m        DSGE.[1;31mupdate![m(m, parameters)
[35msrc/estimate/smc.jl[m[36m:[m            [1;31mupdate![m(m, parameters, regime_switching = regime_switching)
[35msrc/estimate/smc.jl[m[36m:[m            [1;31mupdate![m(m, parameters, regime_switching = regime_switchin)
[35msrc/estimate/smc.jl[m[36m:[m            [1;31mupdate![m(old_model, para2, regime_switching = old_regime_switching)
[35msrc/estimate/smc.jl[m[36m:[m            for p in para2 # Test correct params updated b/c [1;31mupdate![m assumes ordering is the same
[35msrc/estimate/smc.jl[m[36m:[m            [1;31mupdate![m(old_model, parameters, regime_switching = old_regime_switching)
[35msrc/estimate/smc.jl[m[36m:[m        [1;31mupdate![m(m, load_draws(m, :mode, filestring_addl = filestring_addl))
[35msrc/estimate/smc.jl[m[36m:[m        [1;31mupdate![m(m, particles[i].value)
[35msrc/estimate/smc/initialization.jl[m[36m:[m            [1;31mupdate![m(m, draw)
[35msrc/estimate/smc/initialization.jl[m[36m:[m    [1;31mupdate![m(m, draw_vec)
[35msrc/estimate/smc/mutation.jl[m[36m:[m                [1;31mupdate![m(m, para_new)
[35msrc/estimate/util.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, starting_params)
[35msrc/forecast/drivers.jl[m[36m:[m                    [1;31mupdate![m(m, param_try)
[35msrc/forecast/drivers.jl[m[36m:[m    [1;31mupdate![m(m, params) # Note that params is a Vector{Float64}, not a ParameterVector. This `[1;31mupdate![m` infers if the forecast is regime-switching if length(params) > length(m.parameters)
[35msrc/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m            DSGE.[1;31mupdate![m(m, para)
[35msrc/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m            DSGE.[1;31mupdate![m(m, para)
[35msrc/forecast/wrappers_impulse_responses/observables_identified_dsge_impulse_responses.jl[m[36m:[m            DSGE.[1;31mupdate![m(model, para)
[35msrc/forecast/wrappers_impulse_responses/observables_identified_dsge_impulse_responses.jl[m[36m:[m            DSGE.[1;31mupdate![m(model, para)
[35msrc/forecast/wrappers_impulse_responses/observables_identified_dsge_impulse_responses.jl[m[36m:[m            DSGE.[1;31mupdate![m(model, para)
[35msrc/forecast/wrappers_impulse_responses/var_approx_dsge_impulse_responses.jl[m[36m:[m        DSGE.[1;31mupdate![m(_dsgevar, lags = lags, observables = observables)
[35msrc/forecast/wrappers_impulse_responses/var_approx_dsge_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, lags = lags, observables = observables, shocks = shocks)
[35msrc/forecast/wrappers_impulse_responses/var_approx_dsge_impulse_responses.jl[m[36m:[m        DSGE.[1;31mupdate![m(m, para)
[35msrc/models/var/dsgevar/dsgevar.jl[m[36m:[mcalls `[1;31mupdate![m` on the empty DSGE-VAR
[35msrc/models/var/dsgevar/dsgevar.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevar, shocks = [:rm_sh, :z_sh, :g_sh],
[35msrc/models/var/dsgevar/dsgevar.jl[m[36m:[m    [1;31mupdate![m(m; shocks = shocks, check_valid = false)
[35msrc/models/var/dsgevar/dsgevar.jl[m[36m:[m    [1;31mupdate![m(m; check_valid = false)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevar/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/dsgevecm.jl[m[36m:[mcalls `[1;31mupdate![m` on the empty DSGE-VECM
[35msrc/models/var/dsgevecm/dsgevecm.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevecm, shocks = [:rm_sh, :z_sh, :g_sh],
[35msrc/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    [1;31mupdate![m(m; shocks = shocks, check_valid = false)
[35msrc/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    [1;31mupdate![m(m; check_valid = false)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/models/var/dsgevecm/subspecs.jl[m[36m:[m    [1;31mupdate![m(m; observables = observables, lags = lags, λ = λ)
[35msrc/scenarios/forecast.jl[m[36m:[m    [1;31mupdate![m(m, params)
[35mtest/abstractdsgemodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, para)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsge, oldvals)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsge, oldvals)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, oldvals)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsge, newvals)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, newvals)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsge, oldpvec)
[35mtest/abstractvarmodel.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, oldpvec)
[35mtest/estimate/metropolis_hastings.jl[m[36m:[mDSGE.[1;31mupdate![m(m, mode)
[35mtest/estimate/metropolis_hastings.jl[m[36m:[mDSGE.[1;31mupdate![m(m, mode)
[35mtest/estimate/optimize.jl[m[36m:[mDSGE.[1;31mupdate![m(m, x0)
[35mtest/estimate/optimize.jl[m[36m:[mDSGE.[1;31mupdate![m(m, x0)
[35mtest/estimate/optimize.jl[m[36m:[mDSGE.[1;31mupdate![m(m, x0)
[35mtest/estimate/optimize.jl[m[36m:[mDSGE.[1;31mupdate![m(m, x0)
[35mtest/estimate/posterior.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; observables = [:obs_nominalrate, :obs_gdp, :π_t], lags = 4, λ = 0.5)
[35mtest/estimate/regime_switching_mh.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, h5read(joinpath(path, "..", "reference",
[35mtest/estimate/smc/Brookings_test/util_brookings.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, θ)
[35mtest/estimate/smc/Brookings_test/util_brookings.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, θ)
[35mtest/estimate/smc/initialization.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, para)
[35mtest/estimate/smc/mutation.jl[m[36m:[m    DSGE.[1;31mupdate![m(m, parameters)
[35mtest/estimate/util.jl[m[36m:[mDSGE.[1;31mupdate![m(m, x0)
[35mtest/forecast/multiple_altpol_imperfect_awareness.jl[m[36m:[mDSGE.[1;31mupdate![m(m10, θ10)
[35mtest/forecast/multiple_altpol_imperfect_awareness.jl[m[36m:[mDSGE.[1;31mupdate![m(m, update_vals) # make sure parameters match Model 1002 ss10, w/zeros for other parameters
[35mtest/forecast/time_varying_credibility.jl[m[36m:[mDSGE.[1;31mupdate![m(m10, θ10)
[35mtest/forecast/time_varying_credibility.jl[m[36m:[mDSGE.[1;31mupdate![m(m, update_vals) # make sure parameters match Model 1002 ss10, w/zeros for other parameters
[35mtest/forecast/var/dsgevar/impulse_responses.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/forecast/var/dsgevar/impulse_responses.jl[m[36m:[m        DSGE.[1;31mupdate![m(dsgevar, jlddata["modal_param"])
[35mtest/forecast/var/dsgevar/impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/forecast/var/dsgevar/impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, jlddata["modal_param"])
[35mtest/forecast/var/dsgevar/impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, lags = 4, observables = observables, λ = 1.)
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, jlddata["modal_param"])
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, jlddata["modal_param"])
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/forecast/wrappers_impulse_responses/dsgevar_lambda_impulse_responses.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, jlddata["modal_param"])
[35mtest/forecast/wrappers_impulse_responses/observables_identified_dsge_impulse_responses.jl[m[36m:[mDSGE.[1;31mupdate![m(m, θ)
[35mtest/forecast/wrappers_impulse_responses/var_approx_dsge_impulse_responses.jl[m[36m:[mDSGE.[1;31mupdate![m(dsgevar, lags = 4, observables = observables, λ = 1.)
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[mimport DSGE: @test_matrix_approx_eq, [1;31mupdate![m
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:I], Setting(:I, 100))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:amin], Setting(:amin, 0.))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:amax], Setting(:amax, 100.))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:a], Setting(:a, collect(range(0., stop=100., length=100))))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:da], Setting(:da, 100 ./ (100 - 1)))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:aaa], Setting(:aaa, reshape(get_setting(m, :aa), 2 * 100, 1)))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:J], Setting(:J, 2))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:z], Setting(:z, [0.; 1.]))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:dz], Setting(:dz, 1.))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:zz], Setting(:zz, ones(100, 1) * get_setting(m, :z)'))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:zzz], Setting(:zzz, reshape(get_setting(m, :zz), 2 * 100, 1)))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_jump_vars], Setting(:n_jump_vars, length(endo[:value_function])))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars], Setting(:n_state_vars, length(endo[:distribution]) .+ n_shocks_exogenous(m)))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars_unreduce], Setting(:n_state_vars_unreduce, 0))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmax], Setting(:rmin, .0001))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmax], Setting(:rmax, m[:ρ].value))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:r0], Setting(:r0, .005))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:maxit_HJB], Setting(:maxit_HJB, 100))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:crit_HJB], Setting(:crit_HJB, 1e-6))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:Δ_HJB], Setting(:Δ_HJB, 1e4))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:Ir], Setting(:Ir, 100))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:crit_S], Setting(:crit_S, 1e-5))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_state_vars], Setting(:reduce_state_vars, true))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_v], Setting(:reduce_v, true))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:krylov_dim], Setting(:krylov_dim, 5))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_knots], Setting(:n_knots, 12))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:c_power], Setting(:c_power, 7))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:knots_dict], Setting(:knots_dict, Dict(1 => collect(range(get_setting(m, :amin),
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:spline_grid], Setting(:spline_grid, get_setting(m, :a)))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_prior], Setting(:n_prior, 1))
[35mtest/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_post], Setting(:n_post, 2))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:r0], Setting(:r0, .005))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmax], Setting(:rmax, .08 ))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmin], Setting(:rmin, .001))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:ρ0], Setting(:ρ0, .02))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:ρmax], Setting(:ρmax, .05))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:ρmin], Setting(:ρmin, .005))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:iterate_r], Setting(:iterate_r, false))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:iterate_ρ], Setting(:iterate_ρ, true))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:I], Setting(:I, 100))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:amin], Setting(:amin, 0.))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:amax], Setting(:amax, 40.))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:agridparam], Setting(:agridparam, 1))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m#[1;31mupdate![m(m.settings[:a], Setting(:a, construct_asset_grid(get_setting(m, :I), get_setting(m, :agridparam), get_setting(m, :amin), get_setting(m, :amax))))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:J], Setting(:J, 2))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:ygrid_combined], Setting(:ygrid_combined, [0.2, 1.]))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:ymarkov_combined], Setting(:ymarkov_combined, [-.5 .5; .0376 -.0376]))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m#[1;31mupdate![m(m.settings[:g_z] , Setting(:g_z, compute_stationary_income_distribution(get_setting(m, :ymarkov_combined), get_setting(m, :J))))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m#[1;31mupdate![m(m.settings[:zz], Setting(:zz, construct_labor_income_grid(get_setting(m, :ygrid_combined), get_setting(m, :g_z), m[:meanlabeff].value, get_setting(m, :I))))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:z], Setting(:z, get_setting(m, :zz)[1, :]))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_jump_vars], Setting(:n_jump_vars, 201))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars], Setting(:n_state_vars, 200))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars_unreduce], Setting(:n_state_vars_unreduce, 0))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:maxit_HJB], Setting(:maxit_HJB, 500))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:tol_HJB], Setting(:tol_HJB, 1e-8))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:Δ_HJB], Setting(:Δ_HJB, 1e6))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:Ir], Setting(:Ir, 100))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:crit_S], Setting(:crit_S, 1e-5))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:maxit_kfe], Setting(:maxit_kfe, 1000))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:tol_kfe], Setting(:tol_kfe, 1e-12))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:Δ_kfe], Setting(:Δ_kfe, 1e6))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:niter_hours], Setting(:niter_hours, 10))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_state_vars], Setting(:reduce_state_vars, true))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_v], Setting(:reduce_v, true))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:krylov_dim], Setting(:krylov_dim, 20))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_knots], Setting(:n_knots, 12))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:c_power], Setting(:c_power, 1))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:knots_dict], Setting(:knots_dict, Dict(1 => knots)))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:spline_grid], Setting(:spline_grid, get_setting(m, :a)))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_prior], Setting(:n_prior, 1))
[35mtest/models/heterogeneous/one_asset_hank/one_asset_hank.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_post], Setting(:n_post, 2))
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; shocks = [:rm_sh])
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; observables = [:obs_gdp])
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; lags = 1)
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; λ = 0.5)
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    @test_throws ErrorException DSGE.[1;31mupdate![m(m, dsge; shocks = [:not_a_shock])
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    @test_throws ErrorException DSGE.[1;31mupdate![m(m, dsge; observables = [:not_an_observable])
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    @test_throws AssertionError DSGE.[1;31mupdate![m(m, dsge; lags = -1)
[35mtest/models/var/dsgevar/dsgevar.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; observables = [:obs_spread], lags = 1)
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; shocks = [:rm_sh])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; observables = [:obs_gdp])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; lags = 1)
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; λ = 0.5)
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; cointegrating = [:obs_gdp])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; cointegrating_add = [:obs_gdp])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    @test_throws ErrorException DSGE.[1;31mupdate![m(m, dsge; shocks = [:not_a_shock])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    @test_throws ErrorException DSGE.[1;31mupdate![m(m, dsge; observables = [:not_an_observable])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    @test_throws ErrorException DSGE.[1;31mupdate![m(m, dsge; cointegrating = [:not_cointegrating])
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    @test_throws AssertionError DSGE.[1;31mupdate![m(m, dsge; lags = -1)
[35mtest/models/var/dsgevecm/dsgevecm.jl[m[36m:[m    DSGE.[1;31mupdate![m(m; observables = [:obs_spread], lags = 1, cointegrating = [:obs_spread],
[35mtest/parameters.jl[m[36m:[m# Test [1;31mupdate![m with regime switching
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:I], Setting(:I, 100))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:amin], Setting(:amin, 0.))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:amax], Setting(:amax, 100.))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:a], Setting(:a, collect(linspace(0., 100., 100))))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:da], Setting(:da, 100./(100 - 1)))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:aaa], Setting(:aaa, reshape(get_setting(m, :aa), 2 * 100, 1)))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:J], Setting(:J, 2))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:z], Setting(:z, [0., 1.]))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:dz], Setting(:dz, 1.))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:zz], Setting(:zz, ones(100, 1) * get_setting(m, :z)'))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:zzz], Setting(:zzz, reshape(get_setting(m, :zz), 2 * 100, 1)))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_jump_vars], Setting(:n_jump_vars, 200))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars], Setting(:n_state_vars, 199 + 1))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars_unreduce], Setting(:n_state_vars_unreduce, 0))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_state_vars], Setting(:reduce_state_vars, true))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_v], Setting(:reduce_v, true))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:krylov_dim], Setting(:krylov_dim, 5))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_knots], Setting(:n_knots, 12))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:c_power], Setting(:c_power, 7))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:knots_dict], Setting(:knots_dict, Dict(1 => collect(linspace(get_setting(m, :amin), get_setting(m, :amax), 12 - 1)))))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:spline_grid], Setting(:spline_grid, get_setting(m, :a)))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_prior], Setting(:n_prior, 1))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_post], Setting(:n_post, 2))
[35mtest/solve/reduction.jl[m[36m:[m[1;31mupdate![m(m.settings[:F], Setting(:F, identity))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:I], Setting(:I, 100))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:amin], Setting(:amin, 0.))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:amax], Setting(:amax, 100.))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:a], Setting(:a, collect(linspace(0., 100., 100))))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:da], Setting(:da, 100./(100 - 1)))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:aaa], Setting(:aaa, reshape(get_setting(m, :aa), 2 * 100, 1)))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:J], Setting(:J, 2))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:z], Setting(:z, [0., 1.]))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:dz], Setting(:dz, 1.))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:zz], Setting(:zz, ones(100, 1) * get_setting(m, :z)'))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:zzz], Setting(:zzz, reshape(get_setting(m, :zz), 2 * 100, 1)))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_jump_vars], Setting(:n_jump_vars, length(m.endogenous_states[:value_function])))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars], Setting(:n_state_vars, length(m.endogenous_states[:distribution]) + n_shocks_exogenous(m)))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_state_vars_unreduce], Setting(:n_state_vars_unreduce, 0))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmax], Setting(:rmin, .0001))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:rmax], Setting(:rmax, m[:ρ].value))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:r0], Setting(:r0, .005))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:maxit_HJB], Setting(:maxit_HJB, 100))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:crit_HJB], Setting(:crit_HJB, 1e-6))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:Δ_HJB], Setting(:Δ_HJB, 1e4))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:Ir], Setting(:Ir, 100))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:crit_S], Setting(:crit_S, 1e-5))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_state_vars], Setting(:reduce_state_vars, true))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:reduce_v], Setting(:reduce_v, true))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:krylov_dim], Setting(:krylov_dim, 5))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_knots], Setting(:n_knots, 12))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:c_power], Setting(:c_power, 7))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:knots_dict], Setting(:knots_dict, Dict(1 => collect(linspace(get_setting(m, :amin), get_setting(m, :amax), 12 - 1)))))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:spline_grid], Setting(:spline_grid, get_setting(m, :a)))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_prior], Setting(:n_prior, 1))
[35mtest/solve/solve_ct.jl[m[36m:[m[1;31mupdate![m(m.settings[:n_post], Setting(:n_post, 2))
[35mtest/statespace/statespace.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, shocks = collect(keys(m.exogenous_shocks)),
[35mtest/statespace/statespace.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, shocks = collect(keys(m.exogenous_shocks)),
[35mtest/statespace/statespace.jl[m[36m:[m    DSGE.[1;31mupdate![m(dsgevar, λ = 1.)
[35mtest/statespace/statespace.jl[m[36m:[m    # DSGE.[1;31mupdate![m(dsgevecm, shocks = collect(keys(m.exogenous_shocks)),
