using DSGE, ModelConstructors, Test, JLD2, Random, SparseArrays

# You should set regenerate_output = true only when you don't want to match the output
# from the original implemenation by Bayer, Born, and Luetticke.
# If you want to regenerate the output from Bayer, Born, and Luetticke's implementation,
# see the script regen_bbl_output. Note that the seed used in this script
# and regen_bbl_output should match, or else the computed steady state
# will not be the same (at least when the distribution over idiosyncratic states
# is computed using KrylovKit).
#
# You can set regenerate_find_steadystate to true
# if you want to regenerate the output of find_steadystate.
# It requires regenerate_output = true b/c it affects other output,
# so some tests may fail unless all output is regenerated.
regenerate_output = false
regenerate_find_steadystate = false
replicate_original_output = false
if regenerate_output
    assert_str =  "regenerate_output and replicate_original_output cannot both be true b/c " *
        "the output generated by this script is not meant to exactly match the output " *
        "from the original code implemented by Bayer, Born, and Luetticke. Instead, " *
        "the generated output is meant to help test the DSGE.jl implementation " *
        "more quickly, as matching the original code requires running the steady state " *
        "code due to the requirement of seeding before calling steadystate!, and " *
        "the steady state takes several minutes to compute."
    @assert !replicate_original_output assert_str
end
if regenerate_find_steadystate
    assert_str =  "regenerate_find_steadystate and regenerate_output must both be true b/c " *
        "the output from find_steadystate is used by the rest of the script. Thus, " *
        "some tests may fail if other output is not also regenerated"
    @assert regenerate_output assert_str

end

refpath = joinpath("..", "..", "..", "reference")

# Set up model
m = BayerBornLuetticke("ss0"; custom_settings =
                       Dict{Symbol, Setting}(:save_steadystate => Setting(:save_steadystate, false),
                                             :save_jacobian    => Setting(:save_jacobian, false),
                                             :replicate_original_output =>
                                             Setting(:replicate_original_output, replicate_original_output)))

# Compute steady state
Random.seed!(1793)
if replicate_original_output # run a check that the steady state is correct
    steadystate!(m; verbose = :high)
    include("compare_ss.jl")
    m[:TY_star] = out["TY_star"] # out is defined in compare_ss.jl
    m[:BY_star] = out["BY_star"]
    m[:C_star] = out["C_star"]
    m[:C_l1_star] = out["C_l1_star"]
else # otherwise, just compute steady state quantities implied by KSS, VmSS, VkSS, and distrSS
    if regenerate_find_steadystate
        KSS, VmSS, VkSS, distrSS = DSGE.find_steadystate(m; verbose = :high)
        JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_find_steadystate_output.jld2"), true, true, true, IOStream) do file
            write(file, "KSS", KSS)
            write(file, "VmSS", VmSS)
            write(file, "VkSS", VkSS)
            write(file, "distrSS", distrSS)
        end
    else
        DSGE.init_grids!(m)
    end
    input = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_find_steadystate_output.jld2"), "r")
    DSGE.prepare_linearization(m, input["KSS"], input["VmSS"], input["VkSS"], input["distrSS"]; verbose = :none)
end

# Differentiate all aggregate and heterogeneous equilibrium conditions,
# and apply Klein to the Jacobians
m <= Setting(:linearize_heterogeneous_block, true)
if replicate_original_output
    m <= Setting(:klein_inversion_method, :direct)
end
gx, hx, _ = DSGE.klein(m)

if regenerate_output && !replicate_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_linearize.jld2"), true, true, true, IOStream) do file
        write(file, "A",  m[:A].value)
        write(file, "B",  m[:B].value)
        write(file, "gx", gx)
        write(file, "hx", hx)
    end
end

if replicate_original_output
    linout = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_original_linearize_seed1793.jld2"), "r")

    @testset "Linearization compared against saved output from original code implemented by Bayer, Born, and Luetticke" begin
        @test maximum(abs, m[:A].value - linout["A"]) == 0.
        @test maximum(abs, m[:B].value - linout["B"]) < 1e-14
        @test maximum(abs, gx - linout["gx"])          < 1e-5
        @test maximum(abs, hx - linout["hx"])          < 1e-5
    end
else
    linout = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_linearize.jld2"), "r")

    @testset "Linearization compared against saved output from original code implemented by Bayer, Born, and Luetticke" begin
        @test m[:A].value ≈ linout["A"]
        @test m[:B].value ≈ linout["B"]
        @test gx          ≈ linout["gx"]
        @test hx          ≈ linout["hx"]
    end
end

if replicate_original_output # Extra check here that the aggregate block only update to Jacobians works correctly
    m <= Setting(:linearize_heterogeneous_block, false)
    gx, hx, _ = DSGE.klein(m)

    linout = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_original_linearize_aggr_update_seed1793.jld2"), "r")

    @testset "Linearization compared against saved output from original code implemented by Bayer, Born, and Luetticke" begin
        @test maximum(abs, m[:A].value - linout["A"]) == 0.
        @test maximum(abs, m[:B].value - linout["B"]) < 1e-14
        @test maximum(abs, gx - linout["gx"])         < 1e-5
        @test maximum(abs, hx - linout["hx"])         < 1e-5
    end
end

# Solve the model from start to finish,
# avoid costly linearization of heterogeneous block,
# test the aggregate block linearization only option,
# and check using direct inversion instead of the
# minimum norm method.
m <= Setting(:linearize_heterogeneous_block, false)
m <= Setting(:klein_inversion_method, :direct)
TTT, TTT_jump, RRR, CCC = solve(m; verbose = :none)
if regenerate_output && !replicate_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_state_transition.jld2"), true, true, true, IOStream) do file
        write(file, "TTT", TTT)
        write(file, "TTT_jump", TTT_jump)
        write(file, "RRR", RRR)
        write(file, "CCC", CCC)
    end
end
if !replicate_original_output
    st_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_state_transition.jld2"), "r")
    @testset "State transition equations for BayerBornLuetticke" begin
        @test TTT ≈ st_out["TTT"]
        @test TTT_jump ≈ st_out["TTT_jump"]
        @test RRR ≈ st_out["RRR"]
        @test CCC ≈ st_out["CCC"]
    end
end

# Update shock values as follows just for the purpose of testing
for (i, k) in enumerate([:σ_A, :σ_Z, :σ_Ψ, :σ_μ_p, :σ_μ_w, :σ_G, :σ_R, :σ_S, :σ_P])
    m[k] = i * .01
end
meas = DSGE.measurement(m, TTT, TTT_jump, RRR, CCC)
if regenerate_output && !replicate_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_measurement.jld2"), true, true, true, IOStream) do file
        write(file, "ZZ", meas[:ZZ])
        write(file, "DD", meas[:DD])
        write(file, "QQ", meas[:QQ])
        write(file, "EE", meas[:EE])
    end
end
if replicate_original_output
    meas_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_original_measurement.jld2"), "r")
    RQR = RRR * meas[:QQ] * RRR'
    @testset "Measurement equations compared to the original implementation by Bayer, Born, and Luetticke" begin
        reshaped_ZZ = meas[:ZZ][[1, 3, 2, 5, 4, 7, 6, 8, 9, 11, 10], :] # need to re-order measurement equation to match original code
        @test reshaped_ZZ ≈ meas_out["H_sel"]
        @test RQR[1:DSGE.n_backward_looking_states(m), 1:DSGE.n_backward_looking_states(m)] ≈ meas_out["SCov"]
        @test meas[:DD] ≈ zeros(size(meas[:DD]))
    end
else
    meas_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_measurement.jld2"), "r")
    @testset "Measurement equations for BayerBornLuetticke" begin
        @test meas[:ZZ] ≈ meas_out["ZZ"]
        @test meas[:DD] ≈ meas_out["DD"]
        @test meas[:QQ] ≈ meas_out["QQ"]
        @test meas[:EE] ≈ meas_out["EE"]
    end
end

# Now test solve and measurement w/out tracking jumps as model states
m <= Setting(:klein_track_backward_looking_states_only, true)
TTT, TTT_jump, RRR, CCC = solve(m; verbose = :none)
if regenerate_output && !replicate_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_state_transition_states_only.jld2"), true, true, true, IOStream) do file
        write(file, "TTT", TTT)
        write(file, "TTT_jump", TTT_jump)
        write(file, "RRR", RRR)
        write(file, "CCC", CCC)
    end
end
if !replicate_original_output
    st_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_state_transition_states_only.jld2"), "r")
    @testset "State transition equations for BayerBornLuetticke" begin
        @test TTT ≈ st_out["TTT"]
        @test TTT_jump ≈ st_out["TTT_jump"]
        @test RRR ≈ st_out["RRR"]
        @test CCC ≈ st_out["CCC"]
    end
end

for (i, k) in enumerate([:σ_A, :σ_Z, :σ_Ψ, :σ_μ_p, :σ_μ_w, :σ_G, :σ_R, :σ_S, :σ_P])
    m[k] = i * .01
end
meas = DSGE.measurement(m, TTT, TTT_jump, RRR, CCC)
if regenerate_output && !replicate_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_measurement_states_only.jld2"), true, true, true, IOStream) do file
        write(file, "ZZ", meas[:ZZ])
        write(file, "DD", meas[:DD])
        write(file, "QQ", meas[:QQ])
        write(file, "EE", meas[:EE])
    end
end
if !replicate_original_output
    meas_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_measurement_states_only.jld2"), "r")
    @testset "Measurement equations for BayerBornLuetticke" begin
        @test meas[:ZZ] ≈ meas_out["ZZ"]
        @test meas[:DD] ≈ meas_out["DD"]
        @test meas[:QQ] ≈ meas_out["QQ"]
        @test meas[:EE] ≈ meas_out["EE"]
    end
end

# Check sparse jacobian
m <= Setting(:use_sparse_jacobian, true)
m <= Setting(:sparsity_pattern, sparse(get_setting(m, :aggregate_block_jacobian)))
dense_A = copy(m[:A].value)
dense_B = copy(m[:B].value)
DSGE.jacobian(m)
@testset "Sparse differentiation for Jacobian" begin
    @test dense_A ≈ m[:A].value
    @test dense_B ≈ m[:B].value
end
