using DSGE, ModelConstructors, Test, JLD2, Random

# regen output only when you don't want to match the original output
regenerate_output = true
match_original_output = false
if regenerate_output
    assert_str =  "regenerate_output and match_original_output cannot both be true b/c " *
        "the output generated by this script is not meant to exactly match the output " *
        "from the original code implemented by Bayer, Born, and Luetticke. Instead, " *
        "the generated output is meant to help test the DSGE.jl implementation " *
        "more quickly, as matching the original code requires running the steady state " *
        "code due to the requirement of seeding before calling steadystate!, and " *
        "the steady state takes several minutes to compute."
    @assert !match_original_output assert_str
end
refpath = joinpath("..", "..", "..", "reference")

# Set up model
m = BayerBornLuetticke()
if match_original_output
    Random.seed!(1793)
    steadystate!(m; verbose = :high)
    include("compare_ss.jl")
    m[:TY_star] = out["TY_star"] # out is defined in compare_ss.jl
    m[:BY_star] = out["BY_star"]
    m[:C_star] = out["C_star"]
    m[:C_l1_star] = out["C_l1_star"]
else
    DSGE.init_grids!(m)
    input = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_find_steadystate_output.jld2"), "r")
    DSGE.prepare_linearization(m, input["KSS"], input["VmSS"], input["VkSS"], input["distrSS"]; verbose = :none)
end

# TODO: Add the compare_ss.jl script as well as code to regenerate its output


# Apply Klein to m
m <= Setting(:linearize_heterogeneous_blocks, true)
if match_original_output
    m <= Setting(:klein_inversion_method, :direct)
end
gx, hx, _ = DSGE.klein(m)

if regenerate_output && !match_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_linearize.jld2"), true, true, true, IOStream) do file
        write(file, "A",  m[:A].value)
        write(file, "B",  m[:B].value)
        write(file, "gx", gx)
        write(file, "hx", hx)
    end
end

if match_original_output
    linout = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_original_linearize_seed1793.jld2"), "r")

    @testset "Linearization compared against saved output from original code implemented by Bayer, Born, and Luetticke" begin
        @test maximum(abs, m[:A].value - linout["A"]) == 0.
        @test maximum(abs, m[:B].value - linout["B"]) == 0.
        @test maximum(abs, gx - linout["gx"])          < 1e-5
        @test maximum(abs, hx - linout["hx"])          < 1e-5
    end
else
    linout = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_linearize.jld2"), "r")

    @testset "Linearization compared against saved output from original code implemented by Bayer, Born, and Luetticke" begin
        @test m[:A].value ≈ linout["A"]
        @test m[:B].value ≈ linout["B"]
        @test gx          ≈ linout["gx"]
        @test hx          ≈ linout["hx"]
    end
end

# TODO: need to save a linearization where we only call SGU_estim
# and add a test here for that, too, so we know our implementation
# of the aggregate only update is correct.

# Solve the model from start to finish,
# avoid costly linearization of heterogeneous blocks,
# test the aggregate block linearization only option,
# and check using direct inversion instead of the
# minimum norm method.
m <= Setting(:linearize_heterogeneous_blocks, false)
m <= Setting(:klein_inversion_method, :direct)
TTT, RRR, CCC = solve(m; verbose = :none)
# TTT2, RRR2 = DSGE.klein_transition_matrices(m, hx, gx)
if regenerate_output && !match_original_output
    JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_statespace.jld2"), true, true, true, IOStream) do file
        write(file, "TTT", TTT)
        write(file, "RRR", RRR)
        write(file, "CCC", CCC)
    end
end
ssm_out = JLD2.jldopen(joinpath(refpath, "bayer_born_luetticke_statespace.jld2"), "r")
@testset begin
    @test TTT ≈ ssm_out["TTT"]
    @test RRR ≈ ssm_out["RRR"]
    @test CCC ≈ ssm_out["CCC"]
end
